# Generated by Django 4.2.30 on 2026-09-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarea_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
